### PR TITLE
Add integration test

### PR DESCRIPTION
**Pull request by bclozel**
This commit adds an integration test that uses the
`WebSocketStompClient` and `SockJsClient` to send STOMP messages to the
server and check for a response message with the dedicated topic.

Also a few changes to refresh the guide:
* disambiguate paths in message mappings, sockjs configuration, topics
and fix guide wrt SockJS server configuration
* use webjars and refresh front-end
* separate client app in a dedicated file and use jquery
* clean dependencies

### CODE REVIEW

**Comment by bclozel** [comment]
@sdeleuze Could you take a quick look at that one before it's merged?

**Comment by gregturn** [comment]
Are dropping idea plugin because IntelliJ natively hands maven and gradle?

**Comment by sdeleuze** [comment]
@bclozel 👍 for the merge, nice changes !

**Comment by bclozel** [comment]
@gregturn Yeah, everything I'm seeing lately points to not using that plugin and letting IDEA handle things.

**Comment by gregturn** [comment]
Ill run a script job to strike it from every guide.

**Pull request merged**
