### PR TITLE
remove duplicate configuration for compatibility

### PR DESCRIPTION
**Pull request by zverbatim**
the same config repeats twice

### CODE REVIEW

**Comment by gregturn** [comment]
Have you signed our CLA? https://github.com/spring-guides/getting-started-guides/wiki#contributing-to-existing-guides

**Comment by zverbatim** [comment]
@gregturn what's CLA for?

**Comment by gregturn** [comment]
It's something we ask anyone to sign that contributes code changes.

**Comment by zverbatim** [comment]
ok. done.

**Comment by gregturn** [comment]
Thanks! We're really close. Can you also path initial/build.gradle as well?

**Comment by zverbatim** [comment]
@gregturn good point. made the change.

**Comment by gregturn** [comment]
Not sure you pushed the latest commit.

**Comment by gregturn** [comment]
Looks like you created a separate branch and submitted another PR. Can you just add to this one? It keeps the history simple.

**Comment by zverbatim** [comment]
merged the patch-2 to this one.

**Comment by gregturn** [comment]
Thanks! I'll take it from here.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-messaging-stomp-websocket/commit/40eaccb7da8def8db7ff78b6fa0edb28b501f6e3

**Comment by gregturn** [comment]
Thanks!

**Pull request closed without merging**
