### PR TITLE
!= to !==

### PR DESCRIPTION
**Pull request by yujunhao8831**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@yujunhao8831 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-messaging-stomp-websocket&pullRequestId=39)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-messaging-stomp-websocket&pullRequestId=39) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gregturn** [comment]
Obvious fix

**Comment by pivotal-issuemaster** [comment]
@yujunhao8831 This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by gregturn** [comment]
Thanks @yujunhao8831 !

**Pull request merged**
