### PR TITLE
Remove unused form close tag

### PR DESCRIPTION
**Pull request by bluishoul**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bluishoul Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-messaging-stomp-websocket&pullRequestId=40)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-messaging-stomp-websocket&pullRequestId=40) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gregturn** [comment]
What's the basis for this change?

**Comment by pivotal-issuemaster** [comment]
@bluishoul Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-messaging-stomp-websocket&pullRequestId=40)!

**Comment by bluishoul** [comment]
@gregturn The inspection of WebStorm shows me this below.

ac9dd2c4-c33b-421e-bd07-746f65dc89e0

**Pull request merged**
